### ISSUE TITLE
[BUG] Colonists can't access items on quantum units for hauling.

### ISSUE THREAD

**Issue by frenchiveruti** [Ratysz/RT_QuantumStorage#4]
So, I believe this is because RimWorld never intended to have 8 items on a single spot, but I'm wondering if there's any way to work around this.

**Comment by Ratysz** [comment]
Reproduction steps? Mod list? Doesn't happen in a clean install.

**Comment by frenchiveruti** [comment]
Must be another mod then, didn't think about it.
Sorry for the inconvenience.
